# This file has been generated by node2nix 1.5.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "amp-0.3.1" = {
      name = "amp";
      packageName = "amp";
      version = "0.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/amp/-/amp-0.3.1.tgz";
        sha1 = "6adf8d58a74f361e82c1fa8d389c079e139fc47d";
      };
    };
    "amp-message-0.1.2" = {
      name = "amp-message";
      packageName = "amp-message";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/amp-message/-/amp-message-0.1.2.tgz";
        sha1 = "a78f1c98995087ad36192a41298e4db49e3dfc45";
      };
    };
    "ansi-regex-2.1.1" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-2.1.1.tgz";
        sha1 = "c3b33ab5ee360d86e0e628f0468ae7ef27d654df";
      };
    };
    "ansi-styles-2.2.1" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-2.2.1.tgz";
        sha1 = "b432dd3358b634cf75e1e4664368240533c1ddbe";
      };
    };
    "anymatch-2.0.0" = {
      name = "anymatch";
      packageName = "anymatch";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/anymatch/-/anymatch-2.0.0.tgz";
        sha512 = "03mjsaw6xk4zhvl17fpqn59j4v2bafqs0yfw5y45hl8x97xlihwvjmcx3icnaamvipplnczymvzg4sb4ixwpzak0k3p21c00nqqxmz6";
      };
    };
    "argparse-1.0.10" = {
      name = "argparse";
      packageName = "argparse";
      version = "1.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/argparse/-/argparse-1.0.10.tgz";
        sha512 = "17fhywmdjcp8g0ys089i5xg26yajkkg9zg8hyry3fghz75b2pq5vdx997dk5p2sc15r9nsj8rmf4f27g81hi92kzj5q86sdmg5ni553";
      };
    };
    "arr-diff-4.0.0" = {
      name = "arr-diff";
      packageName = "arr-diff";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/arr-diff/-/arr-diff-4.0.0.tgz";
        sha1 = "d6461074febfec71e7e15235761a329a5dc7c520";
      };
    };
    "arr-flatten-1.1.0" = {
      name = "arr-flatten";
      packageName = "arr-flatten";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/arr-flatten/-/arr-flatten-1.1.0.tgz";
        sha512 = "2vdly17xk5kw7bfzajrjdnw4ml3wrfblx8064n0i4fxlchcscx2mvnwkq2bnnqvbqvdy4vs9ad462lz0rid7khysly9m9vzjiblly1g";
      };
    };
    "arr-union-3.1.0" = {
      name = "arr-union";
      packageName = "arr-union";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/arr-union/-/arr-union-3.1.0.tgz";
        sha1 = "e39b09aea9def866a8f206e288af63919bae39c4";
      };
    };
    "array-unique-0.3.2" = {
      name = "array-unique";
      packageName = "array-unique";
      version = "0.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/array-unique/-/array-unique-0.3.2.tgz";
        sha1 = "a894b75d4bc4f6cd679ef3244a9fd8f46ae2d428";
      };
    };
    "assign-symbols-1.0.0" = {
      name = "assign-symbols";
      packageName = "assign-symbols";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/assign-symbols/-/assign-symbols-1.0.0.tgz";
        sha1 = "59667f41fadd4f20ccbc2bb96b8d4f7f78ec0367";
      };
    };
    "async-1.5.2" = {
      name = "async";
      packageName = "async";
      version = "1.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/async/-/async-1.5.2.tgz";
        sha1 = "ec6a61ae56480c0c3cb241c95618e20892f9672a";
      };
    };
    "async-2.6.0" = {
      name = "async";
      packageName = "async";
      version = "2.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/async/-/async-2.6.0.tgz";
        sha512 = "0zp4b5788400npi1ixjry5x3a4m21c8pnknk8v731rgnwnjbp5ijmfcf5ppmn1ap4a04md1s9dr8n9ygdvrmiai590v0k6dby1wc1y4";
      };
    };
    "async-each-1.0.1" = {
      name = "async-each";
      packageName = "async-each";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/async-each/-/async-each-1.0.1.tgz";
        sha1 = "19d386a1d9edc6e7c1c85d388aedbcc56d33602d";
      };
    };
    "async-listener-0.6.9" = {
      name = "async-listener";
      packageName = "async-listener";
      version = "0.6.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/async-listener/-/async-listener-0.6.9.tgz";
        sha512 = "28nzlvxq2szg8x1grqqffcfk81k30kd6cpys7ifqa7gp1bikfaljgp4mddvdv9d1namdbyx40q6cy17py1saw4gzvnl7l1c0gypddhk";
      };
    };
    "atob-2.0.3" = {
      name = "atob";
      packageName = "atob";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/atob/-/atob-2.0.3.tgz";
        sha1 = "19c7a760473774468f20b2d2d03372ad7d4cbf5d";
      };
    };
    "balanced-match-1.0.0" = {
      name = "balanced-match";
      packageName = "balanced-match";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/balanced-match/-/balanced-match-1.0.0.tgz";
        sha1 = "89b4d199ab2bee49de164ea02b89ce462d71b767";
      };
    };
    "base-0.11.2" = {
      name = "base";
      packageName = "base";
      version = "0.11.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/base/-/base-0.11.2.tgz";
        sha512 = "11dwi4v72034dqafp0qxsg8h6cpn92vv4vf909a9fybd69yfg6gqn4hhav6x59r1wbi8h1qlgfh9np0340mpljv1hc9v9p02giqygp5";
      };
    };
    "binary-extensions-1.11.0" = {
      name = "binary-extensions";
      packageName = "binary-extensions";
      version = "1.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/binary-extensions/-/binary-extensions-1.11.0.tgz";
        sha1 = "46aa1751fb6a2f93ee5e689bb1087d4b14c6c205";
      };
    };
    "blessed-0.1.81" = {
      name = "blessed";
      packageName = "blessed";
      version = "0.1.81";
      src = fetchurl {
        url = "https://registry.npmjs.org/blessed/-/blessed-0.1.81.tgz";
        sha1 = "f962d687ec2c369570ae71af843256e6d0ca1129";
      };
    };
    "brace-expansion-1.1.11" = {
      name = "brace-expansion";
      packageName = "brace-expansion";
      version = "1.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.11.tgz";
        sha512 = "248cnpbbf0p32h53rd3g8wzpgrkaj4p078ra1g6l16f82i6bzkvmhwqan5rk88apbll9ly1476kngd7f7z27i3b3zxpbb3064f8yaw8";
      };
    };
    "braces-2.3.1" = {
      name = "braces";
      packageName = "braces";
      version = "2.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/braces/-/braces-2.3.1.tgz";
        sha512 = "2fpcx8h100fhpaffr6mh5ysp6dv06nl5xkii807fw0c603i15sg3wsxmj63fdn4apxdnn8an2ks883mvrdsv7mfryhfxg1pf1h6bvj8";
      };
    };
    "cache-base-1.0.1" = {
      name = "cache-base";
      packageName = "cache-base";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/cache-base/-/cache-base-1.0.1.tgz";
        sha512 = "36i943khi87af4gif9r6imjgybqxq9cbd69z2h8p2s2j6scfbhrv7j3n591xl982fmyq29rkwh70a6qdcf3v0piwzfh8n2jf571v9q0";
      };
    };
    "chalk-1.1.3" = {
      name = "chalk";
      packageName = "chalk";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-1.1.3.tgz";
        sha1 = "a8115c55e4a702fe4d150abd3872822a7e09fc98";
      };
    };
    "charm-0.1.2" = {
      name = "charm";
      packageName = "charm";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/charm/-/charm-0.1.2.tgz";
        sha1 = "06c21eed1a1b06aeb67553cdc53e23274bac2296";
      };
    };
    "chokidar-2.0.2" = {
      name = "chokidar";
      packageName = "chokidar";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/chokidar/-/chokidar-2.0.2.tgz";
        sha512 = "1kncf65ax274b43r63m0bfbap3j5ah7dn86niqwpzzw6ilvpc7yy0fan14k584lw8ycf4nl78n5gv3bpyr4jrk5j3v441ragk1qfzcp";
      };
    };
    "class-utils-0.3.6" = {
      name = "class-utils";
      packageName = "class-utils";
      version = "0.3.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/class-utils/-/class-utils-0.3.6.tgz";
        sha512 = "1xcqwmfmsbrm2ck76brwiqjmcza655khgh5szh6wngk357i37sgwsga1pbarwzaz9hvzkriqhq6j0z5mv0pmz61cf9wxvk3y5mlzs58";
      };
    };
    "cli-table-redemption-1.0.1" = {
      name = "cli-table-redemption";
      packageName = "cli-table-redemption";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/cli-table-redemption/-/cli-table-redemption-1.0.1.tgz";
        sha512 = "290s4qbv6j3b6xl4g8hcvmsy36gr2s3xmhincaapwb9dzy020ixnmms0j4sanbdrk3faw8fzhzhvkbimfnxis5cw544vivj4ir44daa";
      };
    };
    "collection-visit-1.0.0" = {
      name = "collection-visit";
      packageName = "collection-visit";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/collection-visit/-/collection-visit-1.0.0.tgz";
        sha1 = "4bc0373c164bc3291b4d368c829cf1a80a59dca0";
      };
    };
    "commander-2.13.0" = {
      name = "commander";
      packageName = "commander";
      version = "2.13.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-2.13.0.tgz";
        sha512 = "1h27ar13gbld2jk6wk84irqmyz6ya6b4dzmxb6nq8azyi48iq8pqqyq90jwzxqb3i7j167y5fpiys6v7vvjzhm8bbd8rya1kzgr4nri";
      };
    };
    "component-emitter-1.2.1" = {
      name = "component-emitter";
      packageName = "component-emitter";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/component-emitter/-/component-emitter-1.2.1.tgz";
        sha1 = "137918d6d78283f7df7a6b7c5a63e140e69425e6";
      };
    };
    "concat-map-0.0.1" = {
      name = "concat-map";
      packageName = "concat-map";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz";
        sha1 = "d8a96bd77fd68df7793a73036a3ba0d5405d477b";
      };
    };
    "continuation-local-storage-3.2.1" = {
      name = "continuation-local-storage";
      packageName = "continuation-local-storage";
      version = "3.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/continuation-local-storage/-/continuation-local-storage-3.2.1.tgz";
        sha512 = "1jgvfwhxk54pg2rwsz2mz7d7cjghbp7vf2lzibxgfhzkly0cgdi354vxhrqvkvjdg63bmksxv01gxcjn2jli2sc201ajmi7r9qkh7lg";
      };
    };
    "copy-descriptor-0.1.1" = {
      name = "copy-descriptor";
      packageName = "copy-descriptor";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/copy-descriptor/-/copy-descriptor-0.1.1.tgz";
        sha1 = "676f6eb3c39997c2ee1ac3a924fd6124748f578d";
      };
    };
    "core-util-is-1.0.2" = {
      name = "core-util-is";
      packageName = "core-util-is";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.2.tgz";
        sha1 = "b5fd54220aa2bc5ab57aab7140c940754503c1a7";
      };
    };
    "cron-1.3.0" = {
      name = "cron";
      packageName = "cron";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cron/-/cron-1.3.0.tgz";
        sha512 = "3iq9zg5plipbybssrb38lhlqdp1p4mbrmvp92zc477z9ck9k90dnxwgssjzb2a572g801q3c75mwy5hmx1ccmiqf5in6ck0k7n8bx1b";
      };
    };
    "debug-2.6.9" = {
      name = "debug";
      packageName = "debug";
      version = "2.6.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-2.6.9.tgz";
        sha512 = "0q0fsr8bk1m83z0am0h2xn09vyfcf18adscxms8hclznwks1aihsisd96h8npx0idq5wwnypnqrkyk25m5d9zh3dk7rjs29nybc8bkc";
      };
    };
    "debug-3.1.0" = {
      name = "debug";
      packageName = "debug";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-3.1.0.tgz";
        sha512 = "3g1hqsahr1ks2kpvdxrwzr57fj90nnr0hvwwrw8yyyzcv3i11sym8zwibxx67bl1mln0acddrzpkkdjjxnc6n2cm9fazmgzzsl1fzrr";
      };
    };
    "decode-uri-component-0.2.0" = {
      name = "decode-uri-component";
      packageName = "decode-uri-component";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/decode-uri-component/-/decode-uri-component-0.2.0.tgz";
        sha1 = "eb3913333458775cb84cd1a1fae062106bb87545";
      };
    };
    "deep-metrics-0.0.1" = {
      name = "deep-metrics";
      packageName = "deep-metrics";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/deep-metrics/-/deep-metrics-0.0.1.tgz";
        sha512 = "299n30f9ykv8syrz1aai60b31rpj5nqp9fjbd020w7pwdflklkv9hzy2j5sj2gygfra3kf40kmr7yrwlfqbw0c4gyj16nq2k2crczgg";
      };
    };
    "define-property-0.2.5" = {
      name = "define-property";
      packageName = "define-property";
      version = "0.2.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/define-property/-/define-property-0.2.5.tgz";
        sha1 = "c35b1ef918ec3c990f9a5bc57be04aacec5c8116";
      };
    };
    "define-property-1.0.0" = {
      name = "define-property";
      packageName = "define-property";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/define-property/-/define-property-1.0.0.tgz";
        sha1 = "769ebaaf3f4a63aad3af9e8d304c9bbe79bfb0e6";
      };
    };
    "define-property-2.0.2" = {
      name = "define-property";
      packageName = "define-property";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/define-property/-/define-property-2.0.2.tgz";
        sha512 = "1hrk3pzr4hyhfnrjy1msrlj2zh769x4l35q9fq0a2cy2glq3h1iwjkpmvz39y9idwy71h9hd98lydi92485bzkff1dzm70wbr8vc0lg";
      };
    };
    "emitter-listener-1.1.1" = {
      name = "emitter-listener";
      packageName = "emitter-listener";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/emitter-listener/-/emitter-listener-1.1.1.tgz";
        sha1 = "e8bbbe8244bc8e0d0b4ef71cd14294c7f241c7ec";
      };
    };
    "escape-regexp-0.0.1" = {
      name = "escape-regexp";
      packageName = "escape-regexp";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-regexp/-/escape-regexp-0.0.1.tgz";
        sha1 = "f44bda12d45bbdf9cb7f862ee7e4827b3dd32254";
      };
    };
    "escape-string-regexp-1.0.5" = {
      name = "escape-string-regexp";
      packageName = "escape-string-regexp";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.5.tgz";
        sha1 = "1b61c0562190a8dff6ae3bb2cf0200ca130b86d4";
      };
    };
    "eventemitter2-0.4.14" = {
      name = "eventemitter2";
      packageName = "eventemitter2";
      version = "0.4.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/eventemitter2/-/eventemitter2-0.4.14.tgz";
        sha1 = "8f61b75cde012b2e9eb284d4545583b5643b61ab";
      };
    };
    "eventemitter2-1.0.5" = {
      name = "eventemitter2";
      packageName = "eventemitter2";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/eventemitter2/-/eventemitter2-1.0.5.tgz";
        sha1 = "f983610517b1737c0b9dc643beca93893c04df18";
      };
    };
    "expand-brackets-2.1.4" = {
      name = "expand-brackets";
      packageName = "expand-brackets";
      version = "2.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/expand-brackets/-/expand-brackets-2.1.4.tgz";
        sha1 = "b77735e315ce30f6b6eff0f83b04151a22449622";
      };
    };
    "extend-3.0.1" = {
      name = "extend";
      packageName = "extend";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/extend/-/extend-3.0.1.tgz";
        sha1 = "a755ea7bc1adfcc5a31ce7e762dbaadc5e636444";
      };
    };
    "extend-shallow-2.0.1" = {
      name = "extend-shallow";
      packageName = "extend-shallow";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/extend-shallow/-/extend-shallow-2.0.1.tgz";
        sha1 = "51af7d614ad9a9f610ea1bafbb989d6b1c56890f";
      };
    };
    "extend-shallow-3.0.2" = {
      name = "extend-shallow";
      packageName = "extend-shallow";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/extend-shallow/-/extend-shallow-3.0.2.tgz";
        sha1 = "26a71aaf073b39fb2127172746131c2704028db8";
      };
    };
    "extglob-2.0.4" = {
      name = "extglob";
      packageName = "extglob";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/extglob/-/extglob-2.0.4.tgz";
        sha512 = "2klp0045k4wnaspb9khqx90ddv7rjg997mlyp5qz41sl2yqdrpw8g8wji77qq16aawl4yhvg0f993ln48lja0kfmy0wnbh4g50zlrin";
      };
    };
    "fclone-1.0.11" = {
      name = "fclone";
      packageName = "fclone";
      version = "1.0.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/fclone/-/fclone-1.0.11.tgz";
        sha1 = "10e85da38bfea7fc599341c296ee1d77266ee640";
      };
    };
    "fill-range-4.0.0" = {
      name = "fill-range";
      packageName = "fill-range";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fill-range/-/fill-range-4.0.0.tgz";
        sha1 = "d544811d428f98eb06a63dc402d2403c328c38f7";
      };
    };
    "for-in-1.0.2" = {
      name = "for-in";
      packageName = "for-in";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/for-in/-/for-in-1.0.2.tgz";
        sha1 = "81068d295a8142ec0ac726c6e2200c30fb6d5e80";
      };
    };
    "fragment-cache-0.2.1" = {
      name = "fragment-cache";
      packageName = "fragment-cache";
      version = "0.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/fragment-cache/-/fragment-cache-0.2.1.tgz";
        sha1 = "4290fad27f13e89be7f33799c6bc5a0abfff0d19";
      };
    };
    "fs.realpath-1.0.0" = {
      name = "fs.realpath";
      packageName = "fs.realpath";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs.realpath/-/fs.realpath-1.0.0.tgz";
        sha1 = "1504ad2523158caa40db4a2787cb01411994ea4f";
      };
    };
    "fsevents-1.1.3" = {
      name = "fsevents";
      packageName = "fsevents";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/fsevents/-/fsevents-1.1.3.tgz";
        sha512 = "3jw51f4iayxvp9wfxczk1xgcvhsydhlgah64jmpl0mqiii2h8i5pp0lrqac5xn7296gxqrvy4lgm4k4hkifk8gipgqxd68x764gp2jq";
      };
    };
    "get-value-2.0.6" = {
      name = "get-value";
      packageName = "get-value";
      version = "2.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-value/-/get-value-2.0.6.tgz";
        sha1 = "dc15ca1c672387ca76bd37ac0a395ba2042a2c28";
      };
    };
    "gkt-https://tgz.pm2.io/gkt-1.0.0.tgz" = {
      name = "gkt";
      packageName = "gkt";
      version = "1.0.0";
      src = fetchurl {
        name = "gkt-1.0.0.tar.gz";
        url = https://tgz.pm2.io/gkt-1.0.0.tgz;
        sha256 = "c8321f58e753231f612cf72ed04c013ae23c270553d1e800a832fb4e7cf23a00";
      };
    };
    "glob-7.1.2" = {
      name = "glob";
      packageName = "glob";
      version = "7.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-7.1.2.tgz";
        sha512 = "08vjxzixc9dwc1hn5pd60yyij98krk2pr758aiga97r02ncvaqx1hidi95wk470k1v84gg4alls9bm52m77174z128bgf13b61x951h";
      };
    };
    "glob-parent-3.1.0" = {
      name = "glob-parent";
      packageName = "glob-parent";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob-parent/-/glob-parent-3.1.0.tgz";
        sha1 = "9e6af6299d8d3bd2bd40430832bd113df906c5ae";
      };
    };
    "graceful-fs-4.1.11" = {
      name = "graceful-fs";
      packageName = "graceful-fs";
      version = "4.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.1.11.tgz";
        sha1 = "0e8bdfe4d1ddb8854d64e04ea7c00e2a026e5658";
      };
    };
    "has-ansi-2.0.0" = {
      name = "has-ansi";
      packageName = "has-ansi";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-ansi/-/has-ansi-2.0.0.tgz";
        sha1 = "34f5049ce1ecdf2b0649af3ef24e45ed35416d91";
      };
    };
    "has-value-0.3.1" = {
      name = "has-value";
      packageName = "has-value";
      version = "0.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-value/-/has-value-0.3.1.tgz";
        sha1 = "7b1f58bada62ca827ec0a2078025654845995e1f";
      };
    };
    "has-value-1.0.0" = {
      name = "has-value";
      packageName = "has-value";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-value/-/has-value-1.0.0.tgz";
        sha1 = "18b281da585b1c5c51def24c930ed29a0be6b177";
      };
    };
    "has-values-0.1.4" = {
      name = "has-values";
      packageName = "has-values";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-values/-/has-values-0.1.4.tgz";
        sha1 = "6d61de95d91dfca9b9a02089ad384bff8f62b771";
      };
    };
    "has-values-1.0.0" = {
      name = "has-values";
      packageName = "has-values";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-values/-/has-values-1.0.0.tgz";
        sha1 = "95b0b63fec2146619a6fe57fe75628d5a39efe4f";
      };
    };
    "iconv-lite-0.4.19" = {
      name = "iconv-lite";
      packageName = "iconv-lite";
      version = "0.4.19";
      src = fetchurl {
        url = "https://registry.npmjs.org/iconv-lite/-/iconv-lite-0.4.19.tgz";
        sha512 = "0jj1pdq3j9ak8cixn2kjp7ip8hf3xgnb85j4jr32yf9rry620v9072c0kk577mllfk1zl9wzs5ypwzbp7vbhf7j31d5rrqgwb0nldm1";
      };
    };
    "inflight-1.0.6" = {
      name = "inflight";
      packageName = "inflight";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/inflight/-/inflight-1.0.6.tgz";
        sha1 = "49bd6331d7d02d0c09bc910a1075ba8165b56df9";
      };
    };
    "inherits-2.0.3" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.3.tgz";
        sha1 = "633c2c83e3da42a502f52466022480f4208261de";
      };
    };
    "interpret-1.1.0" = {
      name = "interpret";
      packageName = "interpret";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/interpret/-/interpret-1.1.0.tgz";
        sha1 = "7ed1b1410c6a0e0f78cf95d3b8440c63f78b8614";
      };
    };
    "is-3.2.1" = {
      name = "is";
      packageName = "is";
      version = "3.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is/-/is-3.2.1.tgz";
        sha1 = "d0ac2ad55eb7b0bec926a5266f6c662aaa83dca5";
      };
    };
    "is-accessor-descriptor-0.1.6" = {
      name = "is-accessor-descriptor";
      packageName = "is-accessor-descriptor";
      version = "0.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-accessor-descriptor/-/is-accessor-descriptor-0.1.6.tgz";
        sha1 = "a9e12cb3ae8d876727eeef3843f8a0897b5c98d6";
      };
    };
    "is-accessor-descriptor-1.0.0" = {
      name = "is-accessor-descriptor";
      packageName = "is-accessor-descriptor";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-accessor-descriptor/-/is-accessor-descriptor-1.0.0.tgz";
        sha512 = "1qllik6fjwfq17ic0fxwqyll8mrhmcm36xfsq45xc57mq9ah4i4nn4f8fvgb0gx4kpl3jlpkzndp0xlmmf2mh0xmggw6mhw74fng64v";
      };
    };
    "is-binary-path-1.0.1" = {
      name = "is-binary-path";
      packageName = "is-binary-path";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-binary-path/-/is-binary-path-1.0.1.tgz";
        sha1 = "75f16642b480f187a711c814161fd3a4a7655898";
      };
    };
    "is-buffer-1.1.6" = {
      name = "is-buffer";
      packageName = "is-buffer";
      version = "1.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-buffer/-/is-buffer-1.1.6.tgz";
        sha512 = "3kr8dm9qyklmm2xyiz75s8db90bfilfals4x0g276kncihrrrz0ar4y6dqpvc7pwy7h43jay1bayi1r62x97nzvcswkk4ap18pl1irm";
      };
    };
    "is-data-descriptor-0.1.4" = {
      name = "is-data-descriptor";
      packageName = "is-data-descriptor";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-data-descriptor/-/is-data-descriptor-0.1.4.tgz";
        sha1 = "0b5ee648388e2c860282e793f1856fec3f301b56";
      };
    };
    "is-data-descriptor-1.0.0" = {
      name = "is-data-descriptor";
      packageName = "is-data-descriptor";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-data-descriptor/-/is-data-descriptor-1.0.0.tgz";
        sha512 = "0ny6kxc752fg3z6fmj8a7fw2lai2y17d9fx0028nvyv1qj0sa30rfryhv9xd7b7is1yfs0val6amsy2b22rh589il10md36a75mgd4d";
      };
    };
    "is-descriptor-0.1.6" = {
      name = "is-descriptor";
      packageName = "is-descriptor";
      version = "0.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-descriptor/-/is-descriptor-0.1.6.tgz";
        sha512 = "0gbflcxmd30gzj91y19fylsfalirl6qg71sxjximc8lc2vxkg5h9scnahvxsczymchlx742i8ai489843ys431vyw73rp418jpxiw3a";
      };
    };
    "is-descriptor-1.0.2" = {
      name = "is-descriptor";
      packageName = "is-descriptor";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-descriptor/-/is-descriptor-1.0.2.tgz";
        sha512 = "2v1a9mn2rzz52v8vs3i7njk9pv95fh971yc81xr0zkaw3dff4gbv1zv048xyjysfgwpajbyryk2px8hinwwh0wagblmw6chdbjsrs6r";
      };
    };
    "is-extendable-0.1.1" = {
      name = "is-extendable";
      packageName = "is-extendable";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-extendable/-/is-extendable-0.1.1.tgz";
        sha1 = "62b110e289a471418e3ec36a617d472e301dfc89";
      };
    };
    "is-extendable-1.0.1" = {
      name = "is-extendable";
      packageName = "is-extendable";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-extendable/-/is-extendable-1.0.1.tgz";
        sha512 = "0w73qlx9ynmv2iznw1kll86yd04z4rsz3788nzgh7amcnpsbyxbrs734im9dibqgps6pjyz61s8kp4lcsbjsdfrlc51m1pm2hrxgfba";
      };
    };
    "is-extglob-2.1.1" = {
      name = "is-extglob";
      packageName = "is-extglob";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-extglob/-/is-extglob-2.1.1.tgz";
        sha1 = "a88c02535791f02ed37c76a1b9ea9773c833f8c2";
      };
    };
    "is-glob-3.1.0" = {
      name = "is-glob";
      packageName = "is-glob";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-glob/-/is-glob-3.1.0.tgz";
        sha1 = "7ba5ae24217804ac70707b96922567486cc3e84a";
      };
    };
    "is-glob-4.0.0" = {
      name = "is-glob";
      packageName = "is-glob";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-glob/-/is-glob-4.0.0.tgz";
        sha1 = "9521c76845cc2610a85203ddf080a958c2ffabc0";
      };
    };
    "is-number-3.0.0" = {
      name = "is-number";
      packageName = "is-number";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-number/-/is-number-3.0.0.tgz";
        sha1 = "24fd6201a4782cf50561c810276afc7d12d71195";
      };
    };
    "is-number-4.0.0" = {
      name = "is-number";
      packageName = "is-number";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-number/-/is-number-4.0.0.tgz";
        sha512 = "20ybhnkgsrcwv730ch8qvzayjwcvs83jk2w6iim7wv3h2nn4jz8hsldn0k6ggx4xgcypwirqjb5xdacsswsk06w2nk56zr509q2aadd";
      };
    };
    "is-odd-2.0.0" = {
      name = "is-odd";
      packageName = "is-odd";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-odd/-/is-odd-2.0.0.tgz";
        sha512 = "34m1wg28c9l1v9bqz2klwl4ybhyqkhk80d95664jmcbq1jjpg471nv96mqgqy4838xpa8wm7mbpynmq4294pq6iw163s0ar1b3a4f1r";
      };
    };
    "is-plain-object-2.0.4" = {
      name = "is-plain-object";
      packageName = "is-plain-object";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-plain-object/-/is-plain-object-2.0.4.tgz";
        sha512 = "0xgsjz9m3kg5pm36lcchblxk53qay59ya7wi5jgdmz0dsl5b0j2j7wcd48yyfaip1m70mj9aqf8kib02fn62k0hy0vxg2hng60yk4w7";
      };
    };
    "is-windows-1.0.2" = {
      name = "is-windows";
      packageName = "is-windows";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-windows/-/is-windows-1.0.2.tgz";
        sha512 = "0h9a8zw2ddl25yryp7i376iqjdvlsx4gw93sxy4067dw2yi98m3krfwd9xgi9q5w0idw9rqnyhhncr38xsppyi5izkb7ngai58bawkr";
      };
    };
    "isarray-1.0.0" = {
      name = "isarray";
      packageName = "isarray";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-1.0.0.tgz";
        sha1 = "bb935d48582cba168c06834957a54a3e07124f11";
      };
    };
    "isobject-2.1.0" = {
      name = "isobject";
      packageName = "isobject";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isobject/-/isobject-2.1.0.tgz";
        sha1 = "f065561096a3f1da2ef46272f815c840d87e0c89";
      };
    };
    "isobject-3.0.1" = {
      name = "isobject";
      packageName = "isobject";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/isobject/-/isobject-3.0.1.tgz";
        sha1 = "4e431e92b11a9731636aa1f9c8d1ccbcfdab78df";
      };
    };
    "json-stringify-safe-5.0.1" = {
      name = "json-stringify-safe";
      packageName = "json-stringify-safe";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-stringify-safe/-/json-stringify-safe-5.0.1.tgz";
        sha1 = "1296a2d58fd45f19a0f6ce01d65701e2c735b6eb";
      };
    };
    "kind-of-3.2.2" = {
      name = "kind-of";
      packageName = "kind-of";
      version = "3.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/kind-of/-/kind-of-3.2.2.tgz";
        sha1 = "31ea21a734bab9bbb0f32466d893aea51e4a3c64";
      };
    };
    "kind-of-4.0.0" = {
      name = "kind-of";
      packageName = "kind-of";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/kind-of/-/kind-of-4.0.0.tgz";
        sha1 = "20813df3d712928b207378691a45066fae72dd57";
      };
    };
    "kind-of-5.1.0" = {
      name = "kind-of";
      packageName = "kind-of";
      version = "5.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/kind-of/-/kind-of-5.1.0.tgz";
        sha512 = "0zk87sccrjx6pgf9n74v4msnqwq5siyhrkpaklx7yk85ygy5ypcgmyfhbd5mmcyd53x8zcw0gzvp9bhbglziqbhp7a6n5zsf6p08q9l";
      };
    };
    "kind-of-6.0.2" = {
      name = "kind-of";
      packageName = "kind-of";
      version = "6.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/kind-of/-/kind-of-6.0.2.tgz";
        sha512 = "2l91vcracq8y3nxacsssb4yhk0ww011gi5sn55wsb6bpnhyds2i1x98512f61r8awxmj602bxky6c7hsyibjvz17f1pmlf7r4whp6dk";
      };
    };
    "lazy-1.0.11" = {
      name = "lazy";
      packageName = "lazy";
      version = "1.0.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/lazy/-/lazy-1.0.11.tgz";
        sha1 = "daa068206282542c088288e975c297c1ae77b690";
      };
    };
    "lazy-cache-2.0.2" = {
      name = "lazy-cache";
      packageName = "lazy-cache";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/lazy-cache/-/lazy-cache-2.0.2.tgz";
        sha1 = "b9190a4f913354694840859f8a8f7084d8822264";
      };
    };
    "lodash-4.17.5" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.17.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.17.5.tgz";
        sha512 = "11hikgyas884mz8a58vyixaahxbpdwljdw4cb6qp15xa3sfqikp2mm6wgv41jsl34nzsv1hkx9kw3nwczvas5p73whirmaz4sxggwmj";
      };
    };
    "lodash.findindex-4.6.0" = {
      name = "lodash.findindex";
      packageName = "lodash.findindex";
      version = "4.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.findindex/-/lodash.findindex-4.6.0.tgz";
        sha1 = "a3245dee61fb9b6e0624b535125624bb69c11106";
      };
    };
    "lodash.isequal-4.5.0" = {
      name = "lodash.isequal";
      packageName = "lodash.isequal";
      version = "4.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.isequal/-/lodash.isequal-4.5.0.tgz";
        sha1 = "415c4478f2bcc30120c22ce10ed3226f7d3e18e0";
      };
    };
    "lodash.merge-4.6.1" = {
      name = "lodash.merge";
      packageName = "lodash.merge";
      version = "4.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.merge/-/lodash.merge-4.6.1.tgz";
        sha512 = "0lv358i7xyg1hn90fk3xzih5kmj1zlmr759g0hh9fa7npbik629q8h5jd2lvjnrm76ciz92k0yn5z6vcqdbgws1zzsrqzw7ixmk7rh0";
      };
    };
    "map-cache-0.2.2" = {
      name = "map-cache";
      packageName = "map-cache";
      version = "0.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/map-cache/-/map-cache-0.2.2.tgz";
        sha1 = "c32abd0bd6525d9b051645bb4f26ac5dc98a0dbf";
      };
    };
    "map-visit-1.0.0" = {
      name = "map-visit";
      packageName = "map-visit";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/map-visit/-/map-visit-1.0.0.tgz";
        sha1 = "ecdca8f13144e660f1b5bd41f12f3479d98dfb8f";
      };
    };
    "methods-1.1.2" = {
      name = "methods";
      packageName = "methods";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/methods/-/methods-1.1.2.tgz";
        sha1 = "5529a4d67654134edcc5266656835b0f851afcee";
      };
    };
    "micromatch-3.1.9" = {
      name = "micromatch";
      packageName = "micromatch";
      version = "3.1.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromatch/-/micromatch-3.1.9.tgz";
        sha512 = "3vfciram7xbwcwvhii8960vnvf3jczn092sfbfgx1vivk3scvkm9znjnbq2ppywg9h8i86d8vq3ha4c9a3jllaian0gcl7rrgm36lja";
      };
    };
    "minimatch-3.0.4" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-3.0.4.tgz";
        sha512 = "1879a3j85h92ypvb7lpv1dqpcxl49rqnbgs5la18zmj1yqhwl60c2m74254wbr5pp3znckqpkg9dvjyrz6hfz8b9vag5a3j910db4f8";
      };
    };
    "minimist-0.0.8" = {
      name = "minimist";
      packageName = "minimist";
      version = "0.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-0.0.8.tgz";
        sha1 = "857fcabfc3397d2625b8228262e86aa7a011b05d";
      };
    };
    "mixin-deep-1.3.1" = {
      name = "mixin-deep";
      packageName = "mixin-deep";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/mixin-deep/-/mixin-deep-1.3.1.tgz";
        sha512 = "0swcxf279pl5jc4b3d4fm9whbi6sbv2xbcfm1fkxiz793qa2hl5wd1b8dw019dgyidx5nwpa141k0cvvwan0rfypn2am0c4fwn2v4pi";
      };
    };
    "mkdirp-0.5.1" = {
      name = "mkdirp";
      packageName = "mkdirp";
      version = "0.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/mkdirp/-/mkdirp-0.5.1.tgz";
        sha1 = "30057438eac6cf7f8c4767f38648d6697d75c903";
      };
    };
    "moment-2.20.1" = {
      name = "moment";
      packageName = "moment";
      version = "2.20.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/moment/-/moment-2.20.1.tgz";
        sha512 = "2zc9qgzsrnp9g4jm4qsb1g1h7w5zmnkz8690br52l83yr9kwhch0mh7r2vdhc706jkrqczia9wbrgkscz0x6k8cwmb3r5jifbpp47v2";
      };
    };
    "moment-timezone-0.5.14" = {
      name = "moment-timezone";
      packageName = "moment-timezone";
      version = "0.5.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/moment-timezone/-/moment-timezone-0.5.14.tgz";
        sha1 = "4eb38ff9538b80108ba467a458f3ed4268ccfcb1";
      };
    };
    "ms-2.0.0" = {
      name = "ms";
      packageName = "ms";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.0.0.tgz";
        sha1 = "5608aeadfc00be6c2901df5f9861788de0d597c8";
      };
    };
    "mute-stream-0.0.7" = {
      name = "mute-stream";
      packageName = "mute-stream";
      version = "0.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/mute-stream/-/mute-stream-0.0.7.tgz";
        sha1 = "3075ce93bc21b8fab43e1bc4da7e8115ed1e7bab";
      };
    };
    "nan-2.9.2" = {
      name = "nan";
      packageName = "nan";
      version = "2.9.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/nan/-/nan-2.9.2.tgz";
        sha512 = "1iwlv98jbkr46c7hy28crk2m89jiskrp4qfa5ysyacyq8dkbk4hii3cc61irf39b7n6wd9cjlaasmakv9dsknqhb3876zrvrbjvmmcn";
      };
    };
    "nanomatch-1.2.9" = {
      name = "nanomatch";
      packageName = "nanomatch";
      version = "1.2.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/nanomatch/-/nanomatch-1.2.9.tgz";
        sha512 = "1f2indb6hj1h79gxklk6ac2lhfjfydw5ak3v2nwilwir5hqvz9l9kxf63l8k1blsjq4v7r2pf0gqc1b55sqqym5bn9afhrj5xnpvi4z";
      };
    };
    "needle-2.2.0" = {
      name = "needle";
      packageName = "needle";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/needle/-/needle-2.2.0.tgz";
        sha512 = "3ry4wyih9w3nc3d319bmfd9l4jj8fn00lqfs1d00sfy6azvy66yhm6jv411cn1c1zqc01hvj59dlavm82mzxw5mlar8ck9ylz5s0mkq";
      };
    };
    "normalize-path-2.1.1" = {
      name = "normalize-path";
      packageName = "normalize-path";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/normalize-path/-/normalize-path-2.1.1.tgz";
        sha1 = "1ab28b556e198363a8c1a6f7e6fa20137fe6aed9";
      };
    };
    "nssocket-0.6.0" = {
      name = "nssocket";
      packageName = "nssocket";
      version = "0.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/nssocket/-/nssocket-0.6.0.tgz";
        sha1 = "59f96f6ff321566f33c70f7dbeeecdfdc07154fa";
      };
    };
    "object-copy-0.1.0" = {
      name = "object-copy";
      packageName = "object-copy";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-copy/-/object-copy-0.1.0.tgz";
        sha1 = "7e7d858b781bd7c991a41ba975ed3812754e998c";
      };
    };
    "object-visit-1.0.1" = {
      name = "object-visit";
      packageName = "object-visit";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-visit/-/object-visit-1.0.1.tgz";
        sha1 = "f79c4493af0c5377b59fe39d395e41042dd045bb";
      };
    };
    "object.pick-1.3.0" = {
      name = "object.pick";
      packageName = "object.pick";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/object.pick/-/object.pick-1.3.0.tgz";
        sha1 = "87a10ac4c1694bd2e1cbf53591a66141fb5dd747";
      };
    };
    "once-1.4.0" = {
      name = "once";
      packageName = "once";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/once/-/once-1.4.0.tgz";
        sha1 = "583b1aa775961d4b113ac17d9c50baef9dd76bd1";
      };
    };
    "pascalcase-0.1.1" = {
      name = "pascalcase";
      packageName = "pascalcase";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/pascalcase/-/pascalcase-0.1.1.tgz";
        sha1 = "b363e55e8006ca6fe21784d2db22bd15d7917f14";
      };
    };
    "path-dirname-1.0.2" = {
      name = "path-dirname";
      packageName = "path-dirname";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-dirname/-/path-dirname-1.0.2.tgz";
        sha1 = "cc33d24d525e099a5388c0336c6e32b9160609e0";
      };
    };
    "path-is-absolute-1.0.1" = {
      name = "path-is-absolute";
      packageName = "path-is-absolute";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-is-absolute/-/path-is-absolute-1.0.1.tgz";
        sha1 = "174b9268735534ffbc7ace6bf53a5a9e1b5c5f5f";
      };
    };
    "path-parse-1.0.5" = {
      name = "path-parse";
      packageName = "path-parse";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-parse/-/path-parse-1.0.5.tgz";
        sha1 = "3c1adf871ea9cd6c9431b6ea2bd74a0ff055c4c1";
      };
    };
    "pidusage-1.2.0" = {
      name = "pidusage";
      packageName = "pidusage";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pidusage/-/pidusage-1.2.0.tgz";
        sha512 = "0z4d08c458vqawn38g8mvrnfhshscs9aq4ixc4cbwcr3fqmd4lfvzghdslg1j6hyy8yzri62xii9gg7hq6f9dfa4z8q3qx44f4kwsiq";
      };
    };
    "pm2-axon-3.1.0" = {
      name = "pm2-axon";
      packageName = "pm2-axon";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pm2-axon/-/pm2-axon-3.1.0.tgz";
        sha512 = "2nvjybjjkiyshvqr0grcdzwnx0im2xacjn0s5kf61nfkfggazsfmims9674lsr17f54fhr04w44vaw4k29zb2fh5dv2ml7hy7x4rh76";
      };
    };
    "pm2-axon-rpc-0.5.0" = {
      name = "pm2-axon-rpc";
      packageName = "pm2-axon-rpc";
      version = "0.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pm2-axon-rpc/-/pm2-axon-rpc-0.5.0.tgz";
        sha512 = "050jywvmbj595862a6i5npqj8yi37bfawp8b4pa71jyxxv1fkgjfi01n7nsmjkfkchfxd83rn03vplqw4sglzlxnj9izdr2fab81a4c";
      };
    };
    "pm2-deploy-0.3.9" = {
      name = "pm2-deploy";
      packageName = "pm2-deploy";
      version = "0.3.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/pm2-deploy/-/pm2-deploy-0.3.9.tgz";
        sha512 = "26dl4fjw044c1k4wfyn07rpjx7ggwrwwh297drsi9hwgyb4p4f4hd8y91bp5sxn5cmk2d41kqvz7g1b3pdaxbqqxhvb2z7hygjpi091";
      };
    };
    "pm2-multimeter-0.1.2" = {
      name = "pm2-multimeter";
      packageName = "pm2-multimeter";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/pm2-multimeter/-/pm2-multimeter-0.1.2.tgz";
        sha1 = "1a1e55153d41a05534cea23cfe860abaa0eb4ace";
      };
    };
    "pmx-1.6.4" = {
      name = "pmx";
      packageName = "pmx";
      version = "1.6.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/pmx/-/pmx-1.6.4.tgz";
        sha512 = "0p4ngfmyvsrhhv4zzaq8l5hgndpx13k09mdzx20f1sxm92kll5370rvk24gyv61lh9jhrk1j7lc8nn0jpy52ib9hk8kvwnyj48r2kms";
      };
    };
    "posix-character-classes-0.1.1" = {
      name = "posix-character-classes";
      packageName = "posix-character-classes";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/posix-character-classes/-/posix-character-classes-0.1.1.tgz";
        sha1 = "01eac0fe3b5af71a2a6c02feabb8c1fef7e00eab";
      };
    };
    "process-nextick-args-2.0.0" = {
      name = "process-nextick-args";
      packageName = "process-nextick-args";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/process-nextick-args/-/process-nextick-args-2.0.0.tgz";
        sha512 = "0rw8xpqqkhs91722slvzf8icxfaimqp4w8zb3840jxr7r8n8035byl6dhdi5bm0yr6x7sdws0gf3m025fg6hqgaklwlbl4d7bah5l9j";
      };
    };
    "promptly-2.2.0" = {
      name = "promptly";
      packageName = "promptly";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/promptly/-/promptly-2.2.0.tgz";
        sha1 = "2a13fa063688a2a5983b161fff0108a07d26fc74";
      };
    };
    "read-1.0.7" = {
      name = "read";
      packageName = "read";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/read/-/read-1.0.7.tgz";
        sha1 = "b3da19bd052431a97671d44a42634adf710b40c4";
      };
    };
    "readable-stream-2.3.4" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "2.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-2.3.4.tgz";
        sha512 = "1jpffi1v0l7pkzrhh8i9c6cbswa9npyx114cbfncfnzl9d7w9p08k9n703hq5xr2c3rg86qiq023sl1x8y6mawgsxgggy8ccrwk3rmy";
      };
    };
    "readdirp-2.1.0" = {
      name = "readdirp";
      packageName = "readdirp";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/readdirp/-/readdirp-2.1.0.tgz";
        sha1 = "4ed0ad060df3073300c48440373f72d1cc642d78";
      };
    };
    "rechoir-0.6.2" = {
      name = "rechoir";
      packageName = "rechoir";
      version = "0.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/rechoir/-/rechoir-0.6.2.tgz";
        sha1 = "85204b54dba82d5742e28c96756ef43af50e3384";
      };
    };
    "regex-not-1.0.2" = {
      name = "regex-not";
      packageName = "regex-not";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/regex-not/-/regex-not-1.0.2.tgz";
        sha512 = "3cggngaj8m70zdn8kghha4mhvavm7jfy5xm2iqi94w4gi5m5irs3nlrgg975w2231y49jnnw7zhsg648pbkl9zb6vwhii83926q7917";
      };
    };
    "remove-trailing-separator-1.1.0" = {
      name = "remove-trailing-separator";
      packageName = "remove-trailing-separator";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/remove-trailing-separator/-/remove-trailing-separator-1.1.0.tgz";
        sha1 = "c24bce2a283adad5bc3f58e0d48249b92379d8ef";
      };
    };
    "repeat-element-1.1.2" = {
      name = "repeat-element";
      packageName = "repeat-element";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/repeat-element/-/repeat-element-1.1.2.tgz";
        sha1 = "ef089a178d1483baae4d93eb98b4f9e4e11d990a";
      };
    };
    "repeat-string-1.6.1" = {
      name = "repeat-string";
      packageName = "repeat-string";
      version = "1.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/repeat-string/-/repeat-string-1.6.1.tgz";
        sha1 = "8dcae470e1c88abc2d600fff4a776286da75e637";
      };
    };
    "resolve-1.5.0" = {
      name = "resolve";
      packageName = "resolve";
      version = "1.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve/-/resolve-1.5.0.tgz";
        sha512 = "25scf9zkhf5yc9x3d7mfq2im5vyxmq3ih939na6jzblal7mgfcijmadl2maz501mkccykj714gvdhhmlzi86hbk7k03r9ipnwd142l6";
      };
    };
    "resolve-url-0.2.1" = {
      name = "resolve-url";
      packageName = "resolve-url";
      version = "0.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve-url/-/resolve-url-0.2.1.tgz";
        sha1 = "2c637fe77c893afd2a663fe21aa9080068e2052a";
      };
    };
    "ret-0.1.15" = {
      name = "ret";
      packageName = "ret";
      version = "0.1.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/ret/-/ret-0.1.15.tgz";
        sha512 = "2d7igpgyzdlpx2ni0sql8gsnqk9qivfsw6bn1aklm19kbhgxjzmlazz8szfsbdpjka4gk6i3zf0jqa0llaf7dni636fnbwfmyjmhfad";
      };
    };
    "safe-buffer-5.1.1" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.1.1.tgz";
        sha512 = "1p28rllll1w65yzq5azi4izx962399xdsdlfbaynn7vmp981hiss05jhiy9hm7sbbfk3b4dhlcv0zy07fc59mnc07hdv6wcgqkcvawh";
      };
    };
    "safe-regex-1.1.0" = {
      name = "safe-regex";
      packageName = "safe-regex";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-regex/-/safe-regex-1.1.0.tgz";
        sha1 = "40a3669f3b077d1e943d44629e157dd48023bf2e";
      };
    };
    "sax-1.2.4" = {
      name = "sax";
      packageName = "sax";
      version = "1.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/sax/-/sax-1.2.4.tgz";
        sha512 = "1dn291mjsda42w8kldlbmngk6dhjxfbvvd5lckyqmwbjaj6069iq3wx0nvcfglwnpddz2qa93lzf4hv77iz43bd2qixa079sjzl799n";
      };
    };
    "semver-5.5.0" = {
      name = "semver";
      packageName = "semver";
      version = "5.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-5.5.0.tgz";
        sha512 = "0h32zh035y8m6dzcqhcymbhwgmc8839fa1hhj0jfh9ivp9kmqfj1sbwnsnkzcn9qm3sqn38sa8ys2g4c638lpnmzjr0a0qndmv7f8p1";
      };
    };
    "set-getter-0.1.0" = {
      name = "set-getter";
      packageName = "set-getter";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/set-getter/-/set-getter-0.1.0.tgz";
        sha1 = "d769c182c9d5a51f409145f2fba82e5e86e80376";
      };
    };
    "set-immediate-shim-1.0.1" = {
      name = "set-immediate-shim";
      packageName = "set-immediate-shim";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/set-immediate-shim/-/set-immediate-shim-1.0.1.tgz";
        sha1 = "4b2b1b27eb808a9f8dcc481a58e5e56f599f3f61";
      };
    };
    "set-value-0.4.3" = {
      name = "set-value";
      packageName = "set-value";
      version = "0.4.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/set-value/-/set-value-0.4.3.tgz";
        sha1 = "7db08f9d3d22dc7f78e53af3c3bf4666ecdfccf1";
      };
    };
    "set-value-2.0.0" = {
      name = "set-value";
      packageName = "set-value";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/set-value/-/set-value-2.0.0.tgz";
        sha512 = "1xdxg14zh452ih8f7826ki7xpq8wk8a831pm5zngqf8cbc4qv6mr9npks863bfqylfrhm161whf9199rmqn4i12wzmz2ks69z3343c7";
      };
    };
    "shelljs-0.7.8" = {
      name = "shelljs";
      packageName = "shelljs";
      version = "0.7.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/shelljs/-/shelljs-0.7.8.tgz";
        sha1 = "decbcf874b0d1e5fb72e14b164a9683048e9acb3";
      };
    };
    "shimmer-1.2.0" = {
      name = "shimmer";
      packageName = "shimmer";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/shimmer/-/shimmer-1.2.0.tgz";
        sha512 = "1md6jgixa8m30z8lzrf4v2xg5jvkvdgwc3m66pwd6yvw2a8xpywh6qdj76cx1gb906pdy03dyxlrvp3vgy67sk0b622sp11zbdb2c65";
      };
    };
    "snapdragon-0.8.1" = {
      name = "snapdragon";
      packageName = "snapdragon";
      version = "0.8.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/snapdragon/-/snapdragon-0.8.1.tgz";
        sha1 = "e12b5487faded3e3dea0ac91e9400bf75b401370";
      };
    };
    "snapdragon-node-2.1.1" = {
      name = "snapdragon-node";
      packageName = "snapdragon-node";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/snapdragon-node/-/snapdragon-node-2.1.1.tgz";
        sha512 = "2gk18pdld8ij1bpa2mdwl8f7i4rl5d4ys3qw31hipj56wslnsfhp1vxp3q36kj1m4f34wzzlvj0282qx5xlflqf978xyqlc2viyaviv";
      };
    };
    "snapdragon-util-3.0.1" = {
      name = "snapdragon-util";
      packageName = "snapdragon-util";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/snapdragon-util/-/snapdragon-util-3.0.1.tgz";
        sha512 = "1jsaqma4ycl2iq0761i1w7758z1kq7gbsij4xfb7p5cnw0qa62pszv6pr3j856n3pbxww7wwxs5wvcg2cb6vy020kw3bchashqs9clr";
      };
    };
    "source-map-0.5.7" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.5.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.5.7.tgz";
        sha1 = "8a039d2d1021d22d1ea14c80d8ea468ba2ef3fcc";
      };
    };
    "source-map-0.6.1" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.6.1.tgz";
        sha512 = "3p7hw8p69ikj5mwapmqkacsjnbvdfk5ylyamjg9x5izkl717xvzj0vk3fnmx1n4pf54h5rs7r8ig5kk4jv4ycqqj0hv75cnx6k1lf2j";
      };
    };
    "source-map-resolve-0.5.1" = {
      name = "source-map-resolve";
      packageName = "source-map-resolve";
      version = "0.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map-resolve/-/source-map-resolve-0.5.1.tgz";
        sha512 = "3ccyfzn4imm9m891wy0bqh85lxrsf82snlh7dlgvjc28rpd2m6n95x8kjmm2crcpqv6234xc2lqzp1h1cyx7xrn146nzinzzk1bd9fh";
      };
    };
    "source-map-support-0.5.3" = {
      name = "source-map-support";
      packageName = "source-map-support";
      version = "0.5.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map-support/-/source-map-support-0.5.3.tgz";
        sha512 = "3xy2ylp2qm8jwglcsf2fjwvn5w56im64w7yjghyv9ilw2fc5qj65w8h38lpls27m3b5prv8x9cnfmrhkfk7rlb52hmf810ycs0i7abq";
      };
    };
    "source-map-url-0.4.0" = {
      name = "source-map-url";
      packageName = "source-map-url";
      version = "0.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map-url/-/source-map-url-0.4.0.tgz";
        sha1 = "3e935d7ddd73631b97659956d55128e87b5084a3";
      };
    };
    "split-string-3.1.0" = {
      name = "split-string";
      packageName = "split-string";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/split-string/-/split-string-3.1.0.tgz";
        sha512 = "25ih1dx2qb3lawqjxj85znd4l3x8nnigrcdlpfw8064gh2mwxic9bgg5ylgxm9gjl3v8dmyc47rycp8xvqz78jqalg0g9yqj225acrp";
      };
    };
    "sprintf-js-1.0.3" = {
      name = "sprintf-js";
      packageName = "sprintf-js";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/sprintf-js/-/sprintf-js-1.0.3.tgz";
        sha1 = "04e6926f662895354f3dd015203633b857297e2c";
      };
    };
    "sprintf-js-1.1.1" = {
      name = "sprintf-js";
      packageName = "sprintf-js";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/sprintf-js/-/sprintf-js-1.1.1.tgz";
        sha1 = "36be78320afe5801f6cea3ee78b6e5aab940ea0c";
      };
    };
    "static-extend-0.1.2" = {
      name = "static-extend";
      packageName = "static-extend";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/static-extend/-/static-extend-0.1.2.tgz";
        sha1 = "60809c39cbff55337226fd5e0b520f341f1fb5c6";
      };
    };
    "string_decoder-1.0.3" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-1.0.3.tgz";
        sha512 = "22vw5mmwlyblqc2zyqwl39wyhyahhpiyknim8iz5fk6xi002x777gkswiq8fh297djs5ii4pgrys57wq33hr5zf3xfd0d7kjxkzl0g0";
      };
    };
    "strip-ansi-3.0.1" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-3.0.1.tgz";
        sha1 = "6a385fb8853d952d5ff05d0e8aaf94278dc63dcf";
      };
    };
    "supports-color-2.0.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-2.0.0.tgz";
        sha1 = "535d045ce6b6363fa40117084629995e9df324c7";
      };
    };
    "to-object-path-0.3.0" = {
      name = "to-object-path";
      packageName = "to-object-path";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/to-object-path/-/to-object-path-0.3.0.tgz";
        sha1 = "297588b7b0e7e0ac08e04e672f85c1f4999e17af";
      };
    };
    "to-regex-3.0.2" = {
      name = "to-regex";
      packageName = "to-regex";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/to-regex/-/to-regex-3.0.2.tgz";
        sha512 = "03lcq1y1ks55lss37m3cx52f8f4wj85rqsxfxrhi3y8rqa0iiny6df8ardg2f742z870v7xw749lcsxh8yplsmbvaig4rrds1w6asqm";
      };
    };
    "to-regex-range-2.1.1" = {
      name = "to-regex-range";
      packageName = "to-regex-range";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/to-regex-range/-/to-regex-range-2.1.1.tgz";
        sha1 = "7c80c17b9dfebe599e27367e0d4dd5590141db38";
      };
    };
    "tv4-1.3.0" = {
      name = "tv4";
      packageName = "tv4";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/tv4/-/tv4-1.3.0.tgz";
        sha1 = "d020c846fadd50c855abb25ebaecc68fc10f7963";
      };
    };
    "union-value-1.0.0" = {
      name = "union-value";
      packageName = "union-value";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/union-value/-/union-value-1.0.0.tgz";
        sha1 = "5c71c34cb5bad5dcebe3ea0cd08207ba5aa1aea4";
      };
    };
    "unset-value-1.0.0" = {
      name = "unset-value";
      packageName = "unset-value";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/unset-value/-/unset-value-1.0.0.tgz";
        sha1 = "8376873f7d2335179ffb1e6fc3a8ed0dfc8ab559";
      };
    };
    "upath-1.0.4" = {
      name = "upath";
      packageName = "upath";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/upath/-/upath-1.0.4.tgz";
        sha512 = "0xw24ba88hfvwwgniyn17n26av45g1pxqf095231065l4n9dp5w3hyc7azjd8sqyix7pnfx1pmr44fzmwwazkz0ly83cp214g4qk13p";
      };
    };
    "urix-0.1.0" = {
      name = "urix";
      packageName = "urix";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/urix/-/urix-0.1.0.tgz";
        sha1 = "da937f7a62e21fec1fd18d49b35c2935067a6c72";
      };
    };
    "use-2.0.2" = {
      name = "use";
      packageName = "use";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/use/-/use-2.0.2.tgz";
        sha1 = "ae28a0d72f93bf22422a18a2e379993112dec8e8";
      };
    };
    "util-deprecate-1.0.2" = {
      name = "util-deprecate";
      packageName = "util-deprecate";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/util-deprecate/-/util-deprecate-1.0.2.tgz";
        sha1 = "450d4dc9fa70de732762fbd2d4a28981419a0ccf";
      };
    };
    "uuid-3.2.1" = {
      name = "uuid";
      packageName = "uuid";
      version = "3.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/uuid/-/uuid-3.2.1.tgz";
        sha512 = "0843vl1c974n8kw5kn0kvhvhwk8y8jydr0xkwwl2963xxmkw4ingk6xj9c8m48jw2i95giglxzq5aw5v5mij9kv7fzln8pxav1cr6cd";
      };
    };
    "v8-compile-cache-1.1.2" = {
      name = "v8-compile-cache";
      packageName = "v8-compile-cache";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/v8-compile-cache/-/v8-compile-cache-1.1.2.tgz";
        sha512 = "12c2h3b0bwis27ai5ms45j9arh6rm23136ism3gdmjk9ywarnzc46lnpwf8q0a7nmxq2laa8jp1jzw6fvj15yribisx7j88zf4nndvs";
      };
    };
    "vizion-0.2.13" = {
      name = "vizion";
      packageName = "vizion";
      version = "0.2.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/vizion/-/vizion-0.2.13.tgz";
        sha1 = "1314cdee2b34116f9f5b1248536f95dbfcd6ef5f";
      };
    };
    "vxx-1.2.2" = {
      name = "vxx";
      packageName = "vxx";
      version = "1.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/vxx/-/vxx-1.2.2.tgz";
        sha1 = "741fb51c6f11d3383da6f9b92018a5d7ba807611";
      };
    };
    "wrappy-1.0.2" = {
      name = "wrappy";
      packageName = "wrappy";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz";
        sha1 = "b5243d8f3ec1aa35f1364605bc0d1036e30ab69f";
      };
    };
    "yamljs-0.3.0" = {
      name = "yamljs";
      packageName = "yamljs";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/yamljs/-/yamljs-0.3.0.tgz";
        sha512 = "16yrq6cv182wpcxsh7mvvh3r2im856z0cqzjzhfwg38nnzb4g0a37iss23idy3x50h4px4znh8gbksh65x25kl5867qidv1b1anrw8b";
      };
    };
  };
in
{
  pm2 = nodeEnv.buildNodePackage {
    name = "pm2";
    packageName = "pm2";
    version = "2.10.1";
    src = fetchurl {
      url = "https://registry.npmjs.org/pm2/-/pm2-2.10.1.tgz";
      sha512 = "0yfnd6g3jav8kpkjmw7mlsh1y2klchfrwigj5679l7jn0vd5xmyxizvzjj9r65xlqwlr779i616b10a884m93mcxqq37wbl3wg3g5cp";
    };
    dependencies = [
      sources."amp-0.3.1"
      sources."amp-message-0.1.2"
      sources."ansi-regex-2.1.1"
      sources."ansi-styles-2.2.1"
      (sources."anymatch-2.0.0" // {
        dependencies = [
          sources."is-accessor-descriptor-1.0.0"
          sources."is-data-descriptor-1.0.0"
          sources."is-descriptor-1.0.2"
          sources."is-extendable-1.0.1"
        ];
      })
      sources."argparse-1.0.10"
      sources."arr-diff-4.0.0"
      sources."arr-flatten-1.1.0"
      sources."arr-union-3.1.0"
      sources."array-unique-0.3.2"
      sources."assign-symbols-1.0.0"
      sources."async-2.6.0"
      sources."async-each-1.0.1"
      sources."async-listener-0.6.9"
      sources."atob-2.0.3"
      sources."balanced-match-1.0.0"
      (sources."base-0.11.2" // {
        dependencies = [
          (sources."define-property-1.0.0" // {
            dependencies = [
              sources."kind-of-6.0.2"
            ];
          })
          sources."kind-of-3.2.2"
        ];
      })
      sources."binary-extensions-1.11.0"
      sources."blessed-0.1.81"
      sources."brace-expansion-1.1.11"
      (sources."braces-2.3.1" // {
        dependencies = [
          sources."is-accessor-descriptor-1.0.0"
          sources."is-data-descriptor-1.0.0"
          sources."is-descriptor-1.0.2"
        ];
      })
      sources."cache-base-1.0.1"
      sources."chalk-1.1.3"
      sources."charm-0.1.2"
      (sources."chokidar-2.0.2" // {
        dependencies = [
          sources."debug-2.6.9"
          sources."define-property-1.0.0"
          sources."extend-shallow-2.0.1"
          sources."has-values-0.1.4"
          (sources."is-accessor-descriptor-0.1.6" // {
            dependencies = [
              sources."kind-of-3.2.2"
            ];
          })
          (sources."is-data-descriptor-0.1.4" // {
            dependencies = [
              sources."kind-of-3.2.2"
            ];
          })
          sources."is-descriptor-0.1.6"
          sources."is-extendable-0.1.1"
          (sources."is-number-3.0.0" // {
            dependencies = [
              sources."kind-of-3.2.2"
            ];
          })
        ];
      })
      (sources."class-utils-0.3.6" // {
        dependencies = [
          sources."define-property-0.2.5"
        ];
      })
      sources."cli-table-redemption-1.0.1"
      sources."collection-visit-1.0.0"
      sources."commander-2.13.0"
      sources."component-emitter-1.2.1"
      sources."concat-map-0.0.1"
      sources."continuation-local-storage-3.2.1"
      sources."copy-descriptor-0.1.1"
      sources."core-util-is-1.0.2"
      sources."cron-1.3.0"
      sources."debug-3.1.0"
      sources."decode-uri-component-0.2.0"
      sources."deep-metrics-0.0.1"
      sources."define-property-2.0.2"
      sources."emitter-listener-1.1.1"
      sources."escape-regexp-0.0.1"
      sources."escape-string-regexp-1.0.5"
      sources."eventemitter2-1.0.5"
      (sources."expand-brackets-2.1.4" // {
        dependencies = [
          sources."define-property-0.2.5"
        ];
      })
      sources."extend-3.0.1"
      sources."extend-shallow-3.0.2"
      (sources."extglob-2.0.4" // {
        dependencies = [
          sources."define-property-1.0.0"
          sources."extend-shallow-2.0.1"
          sources."kind-of-5.1.0"
        ];
      })
      sources."fclone-1.0.11"
      sources."fill-range-4.0.0"
      sources."for-in-1.0.2"
      sources."fragment-cache-0.2.1"
      sources."fs.realpath-1.0.0"
      sources."fsevents-1.1.3"
      sources."get-value-2.0.6"
      sources."gkt-https://tgz.pm2.io/gkt-1.0.0.tgz"
      sources."glob-7.1.2"
      (sources."glob-parent-3.1.0" // {
        dependencies = [
          sources."is-glob-3.1.0"
        ];
      })
      sources."graceful-fs-4.1.11"
      sources."has-ansi-2.0.0"
      sources."has-value-1.0.0"
      sources."has-values-1.0.0"
      sources."iconv-lite-0.4.19"
      sources."inflight-1.0.6"
      sources."inherits-2.0.3"
      sources."interpret-1.1.0"
      sources."is-3.2.1"
      sources."is-accessor-descriptor-1.0.0"
      sources."is-binary-path-1.0.1"
      sources."is-buffer-1.1.6"
      sources."is-data-descriptor-1.0.0"
      sources."is-descriptor-1.0.2"
      sources."is-extendable-1.0.1"
      sources."is-extglob-2.1.1"
      sources."is-glob-4.0.0"
      sources."is-number-4.0.0"
      sources."is-odd-2.0.0"
      sources."is-plain-object-2.0.4"
      sources."is-windows-1.0.2"
      sources."isarray-1.0.0"
      sources."isobject-3.0.1"
      sources."json-stringify-safe-5.0.1"
      sources."kind-of-6.0.2"
      sources."lazy-1.0.11"
      sources."lazy-cache-2.0.2"
      sources."lodash-4.17.5"
      sources."lodash.findindex-4.6.0"
      sources."lodash.isequal-4.5.0"
      sources."lodash.merge-4.6.1"
      sources."map-cache-0.2.2"
      sources."map-visit-1.0.0"
      sources."methods-1.1.2"
      (sources."micromatch-3.1.9" // {
        dependencies = [
          (sources."is-accessor-descriptor-0.1.6" // {
            dependencies = [
              sources."kind-of-3.2.2"
            ];
          })
          (sources."is-data-descriptor-0.1.4" // {
            dependencies = [
              sources."kind-of-3.2.2"
            ];
          })
          sources."is-descriptor-0.1.6"
          sources."is-extendable-0.1.1"
        ];
      })
      sources."minimatch-3.0.4"
      sources."minimist-0.0.8"
      sources."mixin-deep-1.3.1"
      sources."mkdirp-0.5.1"
      sources."moment-2.20.1"
      sources."moment-timezone-0.5.14"
      sources."ms-2.0.0"
      sources."mute-stream-0.0.7"
      sources."nan-2.9.2"
      sources."nanomatch-1.2.9"
      (sources."needle-2.2.0" // {
        dependencies = [
          sources."debug-2.6.9"
        ];
      })
      sources."normalize-path-2.1.1"
      (sources."nssocket-0.6.0" // {
        dependencies = [
          sources."eventemitter2-0.4.14"
        ];
      })
      sources."object-copy-0.1.0"
      sources."object-visit-1.0.1"
      sources."object.pick-1.3.0"
      sources."once-1.4.0"
      sources."pascalcase-0.1.1"
      sources."path-dirname-1.0.2"
      sources."path-is-absolute-1.0.1"
      sources."path-parse-1.0.5"
      sources."pidusage-1.2.0"
      sources."pm2-axon-3.1.0"
      sources."pm2-axon-rpc-0.5.0"
      (sources."pm2-deploy-0.3.9" // {
        dependencies = [
          sources."async-1.5.2"
        ];
      })
      sources."pm2-multimeter-0.1.2"
      sources."pmx-1.6.4"
      sources."posix-character-classes-0.1.1"
      sources."process-nextick-args-2.0.0"
      sources."promptly-2.2.0"
      sources."read-1.0.7"
      sources."readable-stream-2.3.4"
      sources."readdirp-2.1.0"
      sources."rechoir-0.6.2"
      sources."regex-not-1.0.2"
      sources."remove-trailing-separator-1.1.0"
      sources."repeat-element-1.1.2"
      sources."repeat-string-1.6.1"
      sources."resolve-1.5.0"
      sources."resolve-url-0.2.1"
      sources."ret-0.1.15"
      sources."safe-buffer-5.1.1"
      sources."safe-regex-1.1.0"
      sources."sax-1.2.4"
      sources."semver-5.5.0"
      sources."set-getter-0.1.0"
      sources."set-immediate-shim-1.0.1"
      sources."set-value-2.0.0"
      sources."shelljs-0.7.8"
      sources."shimmer-1.2.0"
      (sources."snapdragon-0.8.1" // {
        dependencies = [
          (sources."define-property-0.2.5" // {
            dependencies = [
              sources."kind-of-5.1.0"
            ];
          })
          sources."extend-shallow-2.0.1"
          sources."kind-of-4.0.0"
        ];
      })
      (sources."snapdragon-node-2.1.1" // {
        dependencies = [
          sources."kind-of-3.2.2"
        ];
      })
      sources."snapdragon-util-3.0.1"
      sources."source-map-0.5.7"
      sources."source-map-resolve-0.5.1"
      (sources."source-map-support-0.5.3" // {
        dependencies = [
          sources."source-map-0.6.1"
        ];
      })
      sources."source-map-url-0.4.0"
      (sources."split-string-3.1.0" // {
        dependencies = [
          sources."extend-shallow-3.0.2"
          sources."is-extendable-1.0.1"
        ];
      })
      sources."sprintf-js-1.1.1"
      sources."static-extend-0.1.2"
      sources."string_decoder-1.0.3"
      sources."strip-ansi-3.0.1"
      sources."supports-color-2.0.0"
      sources."to-object-path-0.3.0"
      sources."to-regex-3.0.2"
      sources."to-regex-range-2.1.1"
      sources."tv4-1.3.0"
      (sources."union-value-1.0.0" // {
        dependencies = [
          sources."set-value-0.4.3"
        ];
      })
      (sources."unset-value-1.0.0" // {
        dependencies = [
          (sources."has-value-0.3.1" // {
            dependencies = [
              sources."isobject-2.1.0"
            ];
          })
        ];
      })
      sources."upath-1.0.4"
      sources."urix-0.1.0"
      sources."use-2.0.2"
      sources."util-deprecate-1.0.2"
      sources."uuid-3.2.1"
      sources."v8-compile-cache-1.1.2"
      (sources."vizion-0.2.13" // {
        dependencies = [
          sources."async-1.5.2"
        ];
      })
      (sources."vxx-1.2.2" // {
        dependencies = [
          sources."debug-2.6.9"
        ];
      })
      sources."wrappy-1.0.2"
      (sources."yamljs-0.3.0" // {
        dependencies = [
          sources."sprintf-js-1.0.3"
        ];
      })
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Production process manager for Node.JS applications with a built-in load balancer.";
      homepage = http://pm2.keymetrics.io/;
      license = "AGPL-3.0";
    };
    production = true;
    bypassCache = true;
  };
}